plugins:
  Enable_Karma_plugin:
    default: true
    client: true
  DAO_name:
    default: ens
    client: true
  Show_Karma_score:
    default: true
    client: true
  Show_delegated_votes:
    default: true
    client: true
  Show_snapshot_votes:
    default: true
    client: true
  Show_on_chain_votes:
    default: true
    client: true
  Show_health_score:
    default: false
    client: true
  User_not_found_message:
    default: Couldn't find stats. Link your wallet to get stats. [[KarmaDaoUrl]]
    client: true
