Karma_Score:
  Enable_Karma_plugin:
    default: true
    client: true
  Karma_API_Key:
    default: ""
    client: false
  Show_Karma_logo:
    default: false
    client: true
  DAO_name:
    default: ens
    client: true
  Show_Karma_score:
    default: true
    client: true
  Show_delegated_votes:
    default: true
    client: true
  Show_snapshot_votes:
    default: true
    client: true
  Show_on_chain_votes:
    default: true
    client: true
  Show_health_score:
    default: false
    client: true
  Show_voting_history:
    default: "3"
    client: true
  User_not_found_message:
    default: Couldn't find stats. Link your wallet to display stats. [[KarmaDaoUrl]]
    client: true
  
Proposal_Banner:
  Show_proposal_banner:
    default: false
    client: true
  Banner_title:
    default: "Active Proposals"
    client: true
  Banner_description:
    default: "See the latest active proposals"
    client: true
  Banner_past_proposal_days:
    default: 0
    client: true
  Show_values_on_proposals:
    default: false
    client: true
  Banner_forum_rules_link:
    default: "/"
    client: true
  Banner_forum_rules_text:
    default: Rules
    client: true
  Banner_forum_rules_icon:
    default: "info-circle"
    client: true
  Banner_gov_docs_link:
    default: "/"
    client: true
  Banner_gov_docs_text:
    default: Gov Docs
    client: true
  Banner_gov_docs_icon:
    default: "palette"
    client: true
  Banner_custom_link:
    default: "/"
    client: true
  Banner_custom_link_text:
    default: "Custom Link"
    client: true
  Banner_custom_link_icon:
    default: "star"
    client: true

Forms:
  Show_delegate_pitch_form:
    default: false
    client: true
  Delegate_pitch_fields:
    default: '[{"label":"Enter your pitch here", "postTitle": "Why should I be a delegate?","type":"text", "placeholder": "Enter your delegate pitch here"},{"label":"Interests","type":"select","options":[{"id":"DAOs","name":"DAOs"},{"id":"Economics","name":"Economics"},{"id":"Governance","name":"Governance"},{"id":"Identity","name":"Identity"},{"id":"Social impact","name":"Social impact"},{"id":"Software Engineering","name":"Software Engineering"}]},{"label":"Languages","type":"select","options":[{"id":"English","name":"English"},{"id":"Mandarin","name":"Mandarin"},{"id":"Hindi","name":"Hindi"},{"id":"Spanish","name":"Spanish"},{"id":"French","name":"French"},{"id":"Arabic","name":"Arabic"},{"id":"Bengali","name":"Bengali"},{"id":"Portuguese","name":"Portuguese"},{"id":"Indonesian","name":"Indonesian"}]}]'
    client: true
  Show_vote_reason_form:
    default: false
    client: true
  # Vote_reason_fields:
  #   default: '[{"label":"Reason","type":"text", "placeholder": "We are in support of this proposal for numerous reasons. The team aligns themselves greatly with DAOs mission. We have voted "Yes" on this proposal."}]'
  #   client: true
  Delegate_pitch_thread_id: 
    default: ""
    client: true
