plugins:
  Enable_Karma_plugin:
    default: true
    client: true
  Show_Karma_logo:
    default: false
    client: true
  DAO_name:
    default: ens
    client: true
  Show_Karma_score:
    default: true
    client: true
  Show_vote_reason_form:
    default: true
    client: true
  Show_delegated_votes:
    default: true
    client: true
  Show_snapshot_votes:
    default: true
    client: true
  Show_on_chain_votes:
    default: true
    client: true
  Show_health_score:
    default: false
    client: true
  Show_voting_history:
    default: "3"
    client: true
  User_not_found_message:
    default: Couldn't find stats. Link your wallet to get stats. [[KarmaDaoUrl]]
    client: true
  Show_proposal_banner:
    default: true
    client: true
  Banner_title:
    default: "Active Proposals"
    client: true
  Banner_description:
    default: "See the latest active proposals"
    client: true
  Banner_past_proposal_days:
    default: 2
    client: true
  Banner_forum_rules_link:
    default: "/"
    client: true
  Banner_forum_rules_text:
    default: Rules
    client: true
  Banner_forum_rules_icon:
    default: "info-circle"
    client: true
  Banner_gov_docs_link:
    default: "/"
    client: true
  Banner_gov_docs_text:
    default: Gov Docs
    client: true
  Banner_gov_docs_icon:
    default: "palette"
    client: true
  Banner_custom_link:
    default: "/"
    client: true
  Banner_custom_link_text:
    default: "Custom Link"
    client: true
  Banner_custom_link_icon:
    default: "star"
    client: true
